<img src= "img/images.png" style="height:87px;">

<div style ="text-align:center;">

# NumPy

<div style="text-align:center">

    Enero 17,2026   
</div>
<img src="img/Python-Logo.jpg" style ="height:400px;">

</div>

*Esteban Sánchez*

## 1. NumPy ndarray
- Es una librería esencial para trabajar con datos numéricos en Python.
- Ofrece arreglos multidimensionales (ndarray) de alto rendimiento, escritos en C.

In [2]:
# Importar librería

import numpy as np

### 1.1 Rendimiento: NumPy vs Python puro
- Operaciones con listas de Python son lentas.

In [3]:
lista = list(range(1000000))

%time lista = [x * 2 for x in lista]

CPU times: total: 62.5 ms
Wall time: 117 ms


- NumPy es mucho más rápido al trabajar con grandes volúmenes de datos.

In [5]:
mi_arr = np.arange(1000000)

%time mi_arr2 = mi_arr*2

CPU times: total: 0 ns
Wall time: 5 ms


### 1.2 Creación de ndarrays

In [6]:
array = np.array([ [2,71,0,34] , [2,171, -35, 34] ])

print (array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [11]:
lista_compra = [['cebollas' , 'zanahorias' , 'apio'] , ['manzanas' , 'naranjas' , 'uvas']]

array = np.array(lista_compra) #lista en array

print(array)
print(type(array))

[['cebollas' 'zanahorias' 'apio']
 ['manzanas' 'naranjas' 'uvas']]
<class 'numpy.ndarray'>


In [10]:
print(np.array([100,10,1]))  # array a partir de una lista

print(np.arange(2,10,2.1)) # array a partir de una secuencia

[100  10   1]
[2.  4.1 6.2 8.3]


In [12]:
# Generar arrays con valores fijos
print(np.zeros(2)) # 1D
print(np.ones((4,3))) # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(3)) # matriz identidad

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 1.3 Información sobre un ndarray
- Se puede obtener:
    - Tamaño (.size)
    - Forma (.shape)
    - Número de dimensiones (.ndim)
    - Índices de valores máximos/mínimos, valores no nulos, etc.

In [13]:
mi_ndarray = np.array([2,71,0,34])
print(mi_ndarray)

[ 2 71  0 34]


In [16]:
print(mi_ndarray.argmax()) # índice del valor más alto
print(np.amax(mi_ndarray))

print(mi_ndarray.argmin()) # índice del valor más bajo
print(np.amin(mi_ndarray))

print(mi_ndarray.nonzero())

1
71
2
0
(array([0, 1, 3]),)


In [32]:
mi_ndarray = np.full((4, 3,2), 2) # matrix 5x2x2
print(mi_ndarray)
print(mi_ndarray.size) # número de elementos
print(mi_ndarray.shape) # dimensiones
print(mi_ndarray.ndim) #número de dimensiones 

[[[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]]
24
(4, 3, 2)
3


#### Redimensionado
- Se puede cambiar la forma con `.reshape()` o convertir a 1D con `.flatten()`

In [33]:
mi_ndarray = np.array([[0,71,21,19,213,412,111,98]])

print (mi_ndarray)
print (mi_ndarray.shape)
print (mi_ndarray.ndim)

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [34]:
new_dims = mi_ndarray.reshape(2,4) #pasa ser de 2 filas y 4 columnas

print(new_dims)
print(new_dims.ndim)

[[  0  71  21  19]
 [213 412 111  98]]
2


In [24]:
new_dims = mi_ndarray.reshape(4,2) #pasa ser de 4 filas y 2 columnas

print(new_dims)
print(new_dims.ndim)

[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [25]:
x = np.array([100,10,1]).reshape(3,1) #cambia las dimensiones  3 filas y 1 columna
print(x.shape)
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [27]:
# redicr a 1D

new_dims= np.arange(9).reshape(3,3)  #cambia las dimensiones a 3x3

print (new_dims)
print (new_dims.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [28]:
# reducir

new_dims = np.arange(16).reshape(4,4)

print(new_dims)
print(new_dims.reshape(2,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## 1.4 Manipular ndarrays
- Funciones como:
    - `.swapaxes()`, `np.flip()`, `.sort()`
    - Combinar con `np.hstack()`, `np.vstack()`, `np.concatenate()`
    - Dividir con `np.array_split()`

In [29]:
# cambiar ejes

new_dims = np.arange(16).reshape(8,2)

print(new_dims)
print(new_dims.swapaxes(0,1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [30]:
# Flip

new_dims = np.arange(16).reshape(4,4)

print(new_dims)
print(np.flip(new_dims, axis = None))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [31]:
# Ordenar

array1 = np.array([10,2,9,17])
array1.sort()

print(array1)

[ 2  9 10 17]


In [45]:
# Juntar 2 arrays

a1= [0,0,0,0,0,0]
a2= [1,1,1,1,1,1]

print(np.hstack((a1,a2)))
print(np.hstack((a1,a2)).shape) #juntar una al lado de otra

print(np.vstack((a1,a2)))
print(np.vstack((a1,a2)).shape) # una encima de la otra

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [46]:
array1 = np.array([[2,4], [6,8]])
array2 = np.array([[3,5], [7,9]])

print(np.concatenate((array1,array2), axis=0))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [47]:
# dividir un array

array = np.arange(16).reshape(4,4)

print(array)
print(np.array_split(array,2,axis=0)) #divide el array en 2 aprtes iguales
print(np.array_split(array,3)) # divide el array en 3 partes

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [48]:
array= np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,[3], axis=1)) #divide al array por la columna 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [50]:
split = np.array_split(array,[3], axis=1)

print(split[0] [3] [0])

12


In [52]:
array = np.arange(64).reshape(8,8)

print(array)
print(np.array_split(array,[1,3], axis = 0))
print(np.array_split(array,[1,3], axis = 1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

## 2. Indices y slicing
- Similar a las listas de Python, pero devuelven vistas (referencias), no copias.
- Permite asignar valores a porciones del arreglo.
- Se puede filtrar con condiciones (máscaras booleanas).

In [56]:
array = np.arange(10,16)

print(array)
print(array[-1])  # acceso unidimensional
print(array[:-1]) #slicing

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [61]:
# acceso bidimensional

array = np.arange(16).reshape(4,4)

print(array)
print(array[2,2])    #fila y columna
print(array[3][2])  #fila y columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [62]:
# multidimensional

array = np.arange(36).reshape(2,3,6)
print(array)
print(array[0,2,4])
print(array[1] [2][4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


#### NumPy es row major

In [63]:
row_major= np.array([1,2,3,4,5,6])

row_major = row_major.reshape(2,3)

print(row_major)

[[1 2 3]
 [4 5 6]]


In [65]:
row_major = np.array([1,2,3,4,5,6])

row_major = row_major.reshape(2,3, order='C')

print(row_major)

col_major = np.array([1,2,3,4,5,6])
col_major = col_major.reshape(2,3, order='F')
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


#### Slice

In [66]:
# se puede hacer slicing por fila o columna

array = np.arange(81).reshape(9,9)

print (array)
print (array[1:3 , 2::2])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [67]:
array = np.arange(9).reshape(3,3)

print(array)
print(array[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


##### Diferencias entre indices y slicing en lista y ndarrays
- Retorna una referencia y no una copia

In [74]:
#uso de slice en listas
lista = [0,1,2,3,4,5,6,7,8,9]
mi_copia = lista[0:2]

print(mi_copia)
mi_copia[0] = 222

print(lista)
print(mi_copia)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [76]:
#slice en ndarrays una referencia en ndarray

array = np.arange(10)
mi_copia = array[2:5]
print (array)
print (mi_copia)


mi_copia [0] = 222

print (array)
print (mi_copia)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [77]:
# copiar arrays 

array = np.arange(10)

mi_copia = array[2:5].copy() #hay que hacer la copia explicitamente

mi_copia[0] = 222

print(array)
print(mi_copia)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


- Permite asignar valores a un corte

In [80]:
array = np.arange(10)

print(array)

print(array[0:3])

array [0:3] = -1
print (array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


- Slicing condicional (mask)

In [82]:
# slicing condicional

array = np.arange(-3,4)
print (array)

mask = array%2 == 0
print(mask)
print(array[mask])

print(array[array%2 == 0])

array[mask] = 0

print(array)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [84]:
array = np.arange(-3,4)
print(array)

array[array<0] = 0
print (array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [85]:
array = np.arange(-3,4)
print(array)

mask = array%2 == 0

print (mask)

array_par = array[mask]

print(array_par)

array_par[0] = -1
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-1  0  2]


- Acceso a múltiples calroes con listados de indices

In [90]:
array = np.arange(0,16).reshape(4,4)

print (array)

print(array[1,2])
print(array[:, [1,2]])

print(array[[1,2] ,:] [:, [1,2]])

print(array[np.ix_([1,2], [1,2])])

ar = array[[2,3,1]]

print(ar)

ar[0] = 990

print (ar)
print (array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[990 990 990 990]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 3. Funciones Matemáticas
- Operaciones entre escalares y arreglos se aplican elemento por elemento
- Soporte para funciones matemáticas como sqrt, exp, log, sin, cos, etc.
- Operaciones entre arreglos: suma, resta, multiplicación, división, comparaciones.

In [92]:
lista = [0,1,2,3]

lista *= 3

print(lista)

lista += [1]
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [98]:
# 
array = np.ones(4, dtype = np.int8)

print(array)

array *=2 
print(array)

array +=10
print(array)
print(array.dtype)

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [104]:
# operacines entre arraya es como poeraciones entre matrices

array1 = np.ones(4) *2 
array2 = np.arange(4)+1

print(array1)
print(array2)

print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[2.         1.         0.66666667 0.5       ]


### 3.1 Broadcasting
- Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande

### 3.2 Operadores unarios y binarios

|Tipo| Operación| Descripción|
|----|----------|-------------|
|Unario| abs| Valor absoluto de cada elemento|
||sqrt|Raiz cuadrada de cada elemento|
||exp| `e^x`x siendo cada elemento
||log, log10, log2| Logaritmos en distintas base de cada elemento|
||sign| Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo)
||ceil| Redondea cada elemento por arriba
||floor| Redondea cada elemento por abajo
|| cos, sin, tan| Operaciones trigonometrcás en cada elemento
|||
|Binario| arccos, arcsin, arctan | Inversas de operaciones trigonometrícas en cada elemento|
|| add| Suma de 2 arrays|
||substract||Resta de 2 arrays|
||multiply| Multiplicación de 2 arrays|
||equal, not equal| Retorna la comparación(igual o no igual) de cada pareja de elementos
||greater, greater_equal, less, less_equal| Retorna la comparación(>, >=, <, <=) respectivamente de cada pareja de elementos

In [105]:
array = np.arange(5)

print(array)
np.sqrt(array)

[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [109]:
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])

print(array1)
print(array2)

print(np.greater(array1, array2))
print(np.less(array2, array1))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


## 4. Estadistica Descriptiva
- Funciones como:
    - sum(), std(), min(), max(), cumsum(), unique(), intersect1d(), etc.
- Se pueden aplicar por filas o columnas con el parámetro axis.

|Función| Descripción|
|-------|------------|
|sum(arr)| Suma de uno delos elementos|
|mean(arr)| Media aritmética de los elementos de arr|
|std(arrr)|Desviación estandar de los elementos de arr|
|cumsum(arr)| Devuelve array con la suma acumualda de todos lso elementos anteriores|
|cumprod(arr)|Devuelve array con el producto acumulado de cada elementos con todos los anteriores|
|min(arr) , max(arr)| Mínimo y máximo de arr
|any(arr) | En array de tipo bool, retorna True si algún elemento es True|
|all(arr) |En array de tipo bool, retorna True si todos los elementos son True (o <>0 en valores numéricos)|
|unique(arr)| Devuelve un array con valores unicos|
|in1d(arr1,arr2)|Devuelve un array con bool indicando si cada elemento de arr1 está en arr2|
|union1d(arr1,arr2)| Devuevle la union de ambos arrays|
|intersect1d(arr1,arr2) | Devuelve la intersección de ambos arrays|

In [110]:
# sum != cumsum

array1 = np.arange(9)

print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [115]:
# any vs all

array1 = np.arange(-8,2).reshape(2,5)

print(array1)
print(array1.any())
print(array1.all())

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [117]:
# todas las funciones acpetan parametros axis

# 0 para columnas , 1 para filas, 2 para profundidad

array1 = np.arange(10).reshape(2,5)

print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


## 5 Algreba lineal
- Funciones en numpy.linalg:
  - Producto punto (dot), multiplicación de matrices (matmul), determinante (det), inversa (inv), autovalores (eig), solución de sistemas (solve), etc.
    
|Funcion | Descripción|
|--------|------------|
|dot(mat1,mat2)| Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas|
|matmul(mat1,mat2)|Devuelve el producto entre 2 matrices|
|trace(mat1,mat2)| Suma de las diagonales de ambas matrices|
|det(mat)| Devuevle el determiante de una matriz|
|eig(mat)| Computa los autovalores y autovectores de la matriz cuadrada mat|
|inv(mat)| Deuvelve la inversa de la matriz|
|gr(mat)| Computa la factorización QR de mat|
|solve(a,b)| Resuelve el sistema lienalde ecuaciones Ax = b para b, cuando A es una matriz cuadrada|
|transpose(mat)| Devuelve la transpuesta de la matriz|

In [118]:
a = np.arange(12).reshape(4,3)
b = np.arange(6).reshape(3,2)

print(a)
print(b)

print(np.matmul(a,b))
print(np.dot(a,b))
print(a@b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [119]:
import numpy.linalg as lg

import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x
11
a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])
b = np.array([12,2,32])
print(a)
print(b)
x,y,z = lg.solve(a,b)
print(f'x={x} y={y} z={z}')
print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x - 3*y - z, 2))
print(math.isclose(2*x -y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [120]:
i = np.arange(4)
print(i)

a = np.arange(16).reshape(4,4)
print(a)

print(np.matmul(a,i))

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[14 38 62 86]


## 6. Filtrado de Datos
- `np.where()` permite reemplazar valores según condiciones.
- Útil para limpiar datos, reemplazar valores inválidos o NaN.

In [121]:
precios = np.array([0.99,14.99,19.99,20.99,0.49])

mask = precios< 1

print(precios[precios < 1])

mask = np.where(precios < 1, True, False)
print(mask)
print(precios[mask])
precios[mask] = 1.0
print(precios)
print(np.where(precios < 1, 1.0, precios))

[0.99 0.49]
[ True False False False  True]
[0.99 0.49]
[ 1.   14.99 19.99 20.99  1.  ]
[ 1.   14.99 19.99 20.99  1.  ]


In [123]:
# Se puede usar para sustituir datos fuera de rango
transferencias = np.array([0.99,-1.49,19.99,20.99,-0.49,12.1]).reshape(2,3)

print(transferencias)

clean_data= np.where(transferencias > 0, transferencias, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [125]:
# Limpiar NaN
data = [10,12,-143, np.nan,1,3]
data_clean = np.where(np.isnan(data), 0 ,data)
print(data_clean)

print(id(data))
print(id(data_clean))

[  10.   12. -143.    0.    1.    3.]
1498558449216
1498558125744


In [127]:
trasnferencias = np.array([0.99,-1.49,19.99,20.99,-0.49,12.1]).reshape(2,3)
print(transferencias)

creditos = np.where(transferencias > 0)

print(creditos)

print(transferencias[creditos])
print(transferencias[transferencias > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [131]:
default = np.arange(6)

print(default) 

upgrade = np.arange(6) * 10

print(upgrade)

puntos_diarios = np.array([0,0,1,6,0,2])
print(puntos_diarios)
final = np.where(puntos_diarios > 1, puntos_diarios, default)
print(final)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[0 1 2 6 4 2]


## 7. Numeros Aleatorios
- `np.random` permite generar números aleatorios con diferentes distribuciones:
    - Uniforme, normal, binomial, Poisson, etc.
- Se puede fijar una semilla (seed) para reproducibilidad.

In [9]:
import random

print(random.random())
print(random.randint(0,5))
print(random.uniform(0,5))

0.6739229698656735
1
3.069248162977589


In [134]:
# elegir un elemento al azar de una coleccion

pokemon = ['Charmander' , 'Squirtle' , 'Bulbasaur']
random.choice(pokemon)

'Charmander'

### 7.1 NumPy.random
- Generar una lista con valores aleatorios

In [137]:
print(np.random.rand()) #valores entre 0 y 1
print(np.random.randint(0,5)) # Integral entre 2 valores
print(np.random.randint(5, size=(2,4))) # parametro "size" para indicar dimensiones

0.8652278096279117
4
[[4 0 2 3]
 [4 2 4 0]]


In [140]:
#array de elementos aleatorios
print(np.random.randn(4,2))

[[-0.81231674 -0.24743247]
 [-1.00037321 -2.01168252]
 [ 0.06423765  0.18996857]
 [-1.1455532  -0.7854206 ]]


In [142]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

0
2.217449676547283
[[3 2]
 [2 0]]


### 7.2 Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [143]:
i = 5 
for _ in range (5) :
    np.random.seed(i)
    print(np.random.randn())
    print(np.random.randn())
print()

for i in range (6):
    np.random.seed(i)
    print(np.random.randn())
    print(np.random.randn())

0.44122748688504143
-0.33087015189408764
0.44122748688504143
-0.33087015189408764
0.44122748688504143
-0.33087015189408764
0.44122748688504143
-0.33087015189408764
0.44122748688504143
-0.33087015189408764

1.764052345967664
0.4001572083672233
1.6243453636632417
-0.6117564136500754
-0.4167578474054706
-0.056266827226329474
1.7886284734303186
0.43650985051198943
0.05056170714293955
0.499951333237829
0.44122748688504143
-0.33087015189408764


## 8. Escritura y lectura de ndarrays a archivos
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [152]:
import os
ruta = os.path.join("res" ,"o_values_array.npy")
values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)

[[5 2 0]
 [7 7 6]
 [0 0 8]]


In [153]:
old_values = np.load(ruta)
print(values)

[[5 2 0]
 [7 7 6]
 [0 0 8]]


In [154]:
ruta = os.path.join("res" ,"o_array_group.npz")
values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3)

In [156]:
npzfile = np.load(ruta)
print(type(npzfile.files))
print(npzfile.files)
for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
    print(npzfile[key])

<class 'list'>
['arr_0', 'arr_1', 'arr_2']
[[5 5 6]
 [4 5 2]
 [8 8 1]]
[[0 3]
 [2 3]]
[[15  4  1 15]
 [ 8  0  2 13]
 [12 11 15  2]
 [ 4  1  6 10]]


### 8.0.1 ¿por qué molestarse con .npy
- Las bases de datos suelen estar en csv o txt, estos requieren lectura con strams
- ¿Para qué escribir los datosde neuvo?

In [160]:
import os
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)
ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [161]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)

%timeit
data = np.load(ruta_npy)

155 ms ± 7.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [163]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")

461 ms ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Ejercicos

2. Imprimir la version de NumPy y su configuración

In [20]:
print(np.__version__)
print(np.show_config())

2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

4. ¿Cómo en contrar el tamaño de memoria de cualquier array?

In [22]:
array = np.zeros(10)
print(a.nbytes)

200


6. Crear un vector null de tamaño de 10 pero el quinto valor es 1

In [3]:
array = np.zeros(10)
print(array)
array[4] = 1

print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


8. Imprimir un vector al revés


In [5]:
array = np.arange(10)

print(array)

print(array[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


10. Encontrar los indices de los elementos que no sean iguales a 0

In [8]:
array = np.array([1,2,0,0,4,0])
index = np.nonzero(array)

print(index)

(array([0, 1, 4]),)


12. Crear una matriz 3x3x3 con valores aleatorios

In [12]:
array = np.random.random((3,3,3))

print(array)

[[[0.24611556 0.7247876  0.14594023]
  [0.11818148 0.48465547 0.77188333]
  [0.17853009 0.66569397 0.20266894]]

 [[0.87119068 0.02448472 0.0269444 ]
  [0.13983086 0.23723278 0.72132403]
  [0.82453129 0.33718978 0.42786888]]

 [[0.6056762  0.2726551  0.18280816]
  [0.42453187 0.91051939 0.0986729 ]
  [0.50270734 0.30007398 0.83648655]]]


14. Crear un vector aleatorio de tamaño 30 y encontrar la media

In [13]:
array = np.random.random(30)

print(array)

media = array.mean()
print(media)

[0.68935273 0.63965718 0.73416002 0.99780561 0.08896571 0.12663602
 0.32514315 0.71656216 0.91838993 0.08482551 0.53131994 0.65197053
 0.70034774 0.24755639 0.48691877 0.31761735 0.66364393 0.85258128
 0.35462847 0.44447443 0.4667683  0.65085383 0.57481596 0.96168055
 0.387716   0.03061782 0.71258006 0.1271923  0.66292978 0.85350425]
0.5333738563757717


16. ¿Cómo añadir un contorno (lleno de 0's) alrededor de un array existente?

In [17]:
array = np.ones((5, 5))

array_ceros = np.zeros((array.shape[0] + 2, array.shape[1] + 2))

array_ceros[1:-1, 1:-1] = array

print(array_ceros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


18. Crear una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal

In [18]:
array = np.zeros((5,5))
valores = [1,2,3,4]
for i in range(len(valores)):   # índice manual
    array[i+1, i] = valores[i]

print (array)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


20. Considdera a (6,7,8) en foramto array, ¿Cuál es el indice(x,y,z) de el elemento 100?

In [19]:
index = np.unravel_index(99, (6, 7, 8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


Repositorio en Github : https://github.com/EstebanSan140106/machine-2.git